Tratamento dos dados brutos 
1 - exportar tabelas csv
- ideia: trocar o código por números ao invés das siglas
- renomear colunas
- tratar nome das entidades
- função para aplicar a mudança de código em todos os dataframes

In [1]:
import pandas as pd
import functions as f

dados_energia = ['data/biofuel-production.csv', 'data/cumulative-installed-wind-energy-capacity-gigawatts.csv', 
                'data/hydro-share-energy.csv', 'data/hydropower-consumption.csv', 'data/installed-geothermal-capacity.csv', 'data/installed-solar-pv-capacity.csv',
                'data/modern-renewable-energy-consumption.csv', 'data/modern-renewable-prod.csv', 'data/renewable-share-energy.csv', 'data/share-electricity-hydro.csv', 
                'data/share-electricity-renewables.csv', 'data/share-electricity-solar.csv', 'data/share-electricity-wind.csv', 'data/solar-energy-consumption.csv',
                'data/solar-share-energy.csv', 'data/wind-generation.csv', 'data/wind-share-energy.csv'] 

nomes_dataframes = ['biocombustivel_produzido', 'eolica_acumulada', 'hidro_compartilhada', 'hidro_consumida', 'capacidade_geotermal', 'capacidade_solar', 
                    'renovavel_consumida', 'renovavel_produzida', 'renovavel_compartilhada', 'hidro_eletricidade_gerada', 'renovavel_eletricidade_gerada', 
                    'solar_eletricidade_gerada', 'eolica_eletricidade_gerada', 'solar_consumida', 'solar_compartilhada', 'eolica_geracao', 'eolica_compartilhada']

len(nomes_dataframes)

17

In [2]:
dfs_energia = f.csv_to_dataframe(dados_energia, nomes_dataframes)

In [3]:
biocombustivel_produzido = dfs_energia['biocombustivel_produzido']
eolica_acumulada = dfs_energia['eolica_acumulada']
hidro_compartilhada = dfs_energia['hidro_compartilhada']
hidro_consumida = dfs_energia['hidro_consumida']
capacidade_geotermal = dfs_energia ['capacidade_geotermal']
capacidade_solar = dfs_energia['capacidade_solar']
renovavel_consumida = dfs_energia['renovavel_consumida']
renovavel_produzida = dfs_energia['renovavel_produzida']
renovavel_compartilhada = dfs_energia['renovavel_compartilhada']
hidro_eletricidade_gerada = dfs_energia['hidro_eletricidade_gerada']
renovavel_eletricidade_gerada = dfs_energia['renovavel_eletricidade_gerada']
solar_eletricidade_gerada = dfs_energia['solar_eletricidade_gerada']
eolica_eletricidade_gerada = dfs_energia['eolica_eletricidade_gerada']
solar_consumida = dfs_energia['solar_consumida']
solar_compartilhada = dfs_energia['solar_compartilhada']
eolica_geracao = dfs_energia['eolica_geracao']
eolica_compartilhada = dfs_energia['eolica_compartilhada']

In [4]:
entidades = f.paises(dfs_energia,nomes_dataframes)
codigo_entidades = {pais: indice + 1 for indice, pais in enumerate(entidades)}
codigo_entidades

{'Africa (EI)': 1,
 'Argentina': 2,
 'Asia': 3,
 'Asia Pacific (EI)': 4,
 'Australia': 5,
 'Austria': 6,
 'Belgium': 7,
 'Brazil': 8,
 'CIS (EI)': 9,
 'Canada': 10,
 'China': 11,
 'Colombia': 12,
 'Europe': 13,
 'Europe (EI)': 14,
 'European Union (27)': 15,
 'Finland': 16,
 'France': 17,
 'Germany': 18,
 'High-income countries': 19,
 'India': 20,
 'Indonesia': 21,
 'Italy': 22,
 'Lower-middle-income countries': 23,
 'Mexico': 24,
 'Middle East (EI)': 25,
 'Netherlands': 26,
 'Non-OECD (EI)': 27,
 'North America': 28,
 'North America (EI)': 29,
 'OECD (EI)': 30,
 'Oceania': 31,
 'Poland': 32,
 'Portugal': 33,
 'South America': 34,
 'South Korea': 35,
 'South and Central America (EI)': 36,
 'Spain': 37,
 'Sweden': 38,
 'Thailand': 39,
 'United Kingdom': 40,
 'United States': 41,
 'Upper-middle-income countries': 42,
 'World': 43,
 'Afghanistan': 44,
 'Africa': 45,
 'Africa (IRENA)': 46,
 'Algeria': 47,
 'Antigua and Barbuda': 48,
 'Armenia': 49,
 'Aruba': 50,
 'Asia (IRENA)': 51,
 'Azerbaijan': 52,
 'Bahrain': 53,
 'Bangladesh': 54,
 'Barbados': 55,
 'Belarus': 56,
 'Belize': 57,
 'Bhutan': 58,
 'Bolivia': 59,
 'Bonaire Sint Eustatius and Saba': 60,
 'Bosnia and Herzegovina': 61,
 'British Virgin Islands': 62,
 'Bulgaria': 63,
 'Cambodia': 64,
 'Cape Verde': 65,
 'Central America and the Caribbean (IRENA)': 66,
 'Chad': 67,
 'Chile': 68,
 'Cook Islands': 69,
 'Costa Rica': 70,
 'Croatia': 71,
 'Cuba': 72,
 'Curacao': 73,
 'Cyprus': 74,
 'Czechia': 75,
 'Denmark': 76,
 'Djibouti': 77,
 'Dominica': 78,
 'Dominican Republic': 79,
 'Ecuador': 80,
 'Egypt': 81,
 'El Salvador': 82,
 'Eritrea': 83,
 'Estonia': 84,
 'Ethiopia': 85,
 'Eurasia (IRENA)': 86,
 'Europe (IRENA)': 87,
 'Falkland Islands': 88,
 'Faroe Islands': 89,
 'Fiji': 90,
 'French Polynesia': 91,
 'Gambia': 92,
 'Georgia': 93,
 'Ghana': 94,
 'Greece': 95,
 'Greenland': 96,
 'Grenada': 97,
 'Guadeloupe': 98,
 'Guam': 99,
 'Guatemala': 100,
 'Guyana': 101,
 'Haiti': 102,
 'Honduras': 103,
 'Hong Kong': 104,
 'Hungary': 105,
 'Iceland': 106,
 'Iran': 107,
 'Ireland': 108,
 'Israel': 109,
 'Jamaica': 110,
 'Japan': 111,
 'Jordan': 112,
 'Kazakhstan': 113,
 'Kenya': 114,
 'Kosovo': 115,
 'Kuwait': 116,
 'Latvia': 117,
 'Lebanon': 118,
 'Lithuania': 119,
 'Low-income countries': 120,
 'Luxembourg': 121,
 'Madagascar': 122,
 'Maldives': 123,
 'Malta': 124,
 'Marshall Islands': 125,
 'Martinique': 126,
 'Mauritania': 127,
 'Mauritius': 128,
 'Micronesia (country)': 129,
 'Middle East (IRENA)': 130,
 'Moldova': 131,
 'Mongolia': 132,
 'Montenegro': 133,
 'Morocco': 134,
 'Myanmar': 135,
 'Namibia': 136,
 'Nepal': 137,
 'New Caledonia': 138,
 'New Zealand': 139,
 'Nicaragua': 140,
 'Nigeria': 141,
 'North America (IRENA)': 142,
 'North Korea': 143,
 'North Macedonia': 144,
 'Norway': 145,
 'Oceania (IRENA)': 146,
 'Oman': 147,
 'Pakistan': 148,
 'Panama': 149,
 'Peru': 150,
 'Philippines': 151,
 'Puerto Rico': 152,
 'Reunion': 153,
 'Romania': 154,
 'Russia': 155,
 'Saint Kitts and Nevis': 156,
 'Saint Pierre and Miquelon': 157,
 'Samoa': 158,
 'Saudi Arabia': 159,
 'Senegal': 160,
 'Serbia': 161,
 'Seychelles': 162,
 'Singapore': 163,
 'Slovakia': 164,
 'Slovenia': 165,
 'Somalia': 166,
 'South Africa': 167,
 'South America (IRENA)': 168,
 'South Georgia and the South Sandwich Islands': 169,
 'Sri Lanka': 170,
 'Switzerland': 171,
 'Syria': 172,
 'Taiwan': 173,
 'Tanzania': 174,
 'Tokelau': 175,
 'Tonga': 176,
 'Trinidad and Tobago': 177,
 'Tunisia': 178,
 'Turkey': 179,
 'Ukraine': 180,
 'United Arab Emirates': 181,
 'United States Virgin Islands': 182,
 'Uruguay': 183,
 'Uzbekistan': 184,
 'Vanuatu': 185,
 'Venezuela': 186,
 'Vietnam': 187,
 'Central America (EI)': 188,
 'Eastern Africa (EI)': 189,
 'Iraq': 190,
 'Malaysia': 191,
 'Middle Africa (EI)': 192,
 'Turkmenistan': 193,
 'USSR': 194,
 'Western Africa (EI)': 195,
 'ASEAN (Ember)': 196,
 'Africa (Ember)': 197,
 'Albania': 198,
 'American Samoa': 199,
 'Angola': 200,
 'Asia (Ember)': 201,
 'Bahamas': 202,
 'Benin': 203,
 'Bermuda': 204,
 'Botswana': 205,
 'Brunei': 206,
 'Burkina Faso': 207,
 'Burundi': 208,
 'Cameroon': 209,
 'Cayman Islands': 210,
 'Central African Republic': 211,
 'Comoros': 212,
 'Congo': 213,
 "Cote d'Ivoire": 214,
 'Democratic Republic of Congo': 215,
 'East Timor': 216,
 'Equatorial Guinea': 217,
 'Eswatini': 218,
 'Europe (Ember)': 219,
 'French Guiana': 220,
 'G20 (Ember)': 221,
 'G7 (Ember)': 222,
 'Gabon': 223,
 'Gibraltar': 224,
 'Guinea': 225,
 'Guinea-Bissau': 226,
 'Kiribati': 227,
 'Kyrgyzstan': 228,
 'Laos': 229,
 'Latin America and Caribbean (Ember)': 230,
 'Lesotho': 231,
 'Liberia': 232,
 'Libya': 233,
 'Macao': 234,
 'Malawi': 235,
 'Mali': 236,
 'Middle East (Ember)': 237,
 'Montserrat': 238,
 'Mozambique': 239,
 'Nauru': 240,
 'Niger': 241,
 'Niue': 242,
 'North America (Ember)': 243,
 'OECD (Ember)': 244,
 'Oceania (Ember)': 245,
 'Palestine': 246,
 'Papua New Guinea': 247,
 'Paraguay': 248,
 'Qatar': 249,
 'Rwanda': 250,
 'Saint Helena': 251,
 'Saint Lucia': 252,
 'Saint Vincent and the Grenadines': 253,
 'Sao Tome and Principe': 254,
 'Sierra Leone': 255,
 'Solomon Islands': 256,
 'South Sudan': 257,
 'Sudan': 258,
 'Suriname': 259,
 'Tajikistan': 260,
 'Togo': 261,
 'Turks and Caicos Islands': 262,
 'Uganda': 263,
 'Western Sahara': 264,
 'Yemen': 265,
 'Zambia': 266,
 'Zimbabwe': 267,
 'Andorra': 268,
 'Anguilla': 269,
 'Mayotte': 270,
 'Palau': 271,
 'Saint Barthelemy': 272,
 'Saint Martin (French part)': 273,
 'Tuvalu': 274}

In [5]:
dfs_energia = f.todos_df(dfs_energia, nomes_dataframes, codigo_entidades)
biocombustivel_produzido = dfs_energia['biocombustivel_produzido']
biocombustivel_produzido.sample(n=5, replace=True)

            Entity  Code  Year  Biofuels production - TWh
689  Non-OECD (EI)    27  2014                 351.989870
847       Portugal    33  2015                   3.729485
791      OECD (EI)    30  2017                 620.445560
117      Australia     5  2018                   1.503534
787      OECD (EI)    30  2013                 516.185800

In [6]:
dfs_energia2 = f.reordenando_colunas(dfs_energia, nomes_dataframes)
dfs_energia2

{'biocombustivel_produzido':       Code       Entity  Year  Biofuels production - TWh
 0        1  Africa (EI)  1990                   0.305102
 1        1  Africa (EI)  1991                   0.305102
 2        1  Africa (EI)  1992                   0.305290
 3        1  Africa (EI)  1993                   0.068617
 4        1  Africa (EI)  1994                   0.068617
 ...    ...          ...   ...                        ...
 1129    43        World  2018                1080.687900
 1130    43        World  2019                1139.786100
 1131    43        World  2020                1071.721200
 1132    43        World  2021                1121.722300
 1133    43        World  2022                1187.204300

 [1134 rows x 4 columns],
 'eolica_acumulada':       Code       Entity  Year  Wind energy capacity
 0       44  Afghanistan  2012               0.00010
 1       44  Afghanistan  2013               0.00010
 2       44  Afghanistan  2014               0.00010
 3       44  Afghanistan  2015               0.00010
 4       44  Afghanistan  2016               0.00010
 ...    ...          ...   ...                   ...
 3054    43        World  2018             564.51290
 3055    43        World  2019             620.84130
 3056    43        World  2020             731.65550
 3057    43        World  2021             824.17090
 3058    43        World  2022             898.82425

 [3059 rows x 4 columns],
 'hidro_compartilhada':       Code  Entity  Year  Hydro (% equivalent primary energy)
 0       45  Africa  1965                             5.740281
 1       45  Africa  1966                             6.113969
 2       45  Africa  1967                             6.316580
 3       45  Africa  1968                             6.994845
 4       45  Africa  1969                             7.943916
 ...    ...     ...   ...                                  ...
 4782    43   World  2018                             6.867884
 4783    43   World  2019                             6.855210
 4784    43   World  2020                             7.275157
 4785    43   World  2021                             6.762651
 4786    43   World  2022                             6.734592

 [4787 rows x 4 columns],
 'hidro_consumida':       Code         Entity  Year  Electricity from hydro (TWh)
 0      196  ASEAN (Ember)  2000                         50.37
 1      196  ASEAN (Ember)  2001                         54.26
 2      196  ASEAN (Ember)  2002                         53.32
 3      196  ASEAN (Ember)  2003                         53.28
 4      196  ASEAN (Ember)  2004                         52.88
 ...    ...            ...   ...                           ...
 8879   267       Zimbabwe  2017                          3.97
 8880   267       Zimbabwe  2018                          5.05
 8881   267       Zimbabwe  2019                          4.17
 8882   267       Zimbabwe  2020                          3.81
 8883   267       Zimbabwe  2021                          4.00

 [8884 rows x 4 columns],
 'capacidade_geotermal':       Code  Entity  Year  Geothermal energy capacity
 0       45  Africa  2000                       65.30
 1       45  Africa  2001                       65.30
 2       45  Africa  2002                       65.30
 3       45  Africa  2003                       65.30
 4       45  Africa  2004                      135.30
 ...    ...     ...   ...                         ...
 1039    43   World  2018                    13471.32
 1040    43   World  2019                    14089.46
 1041    43   World  2020                    14416.76
 1042    43   World  2021                    14695.61
 1043    43   World  2022                    14876.51

 [1044 rows x 4 columns],
 'capacidade_solar':       Code       Entity  Year  Solar energy capacity
 0       44  Afghanistan  2009               0.000002
 1       44  Afghanistan  2010               0.000102
 2       44  Afghanistan  2011               0.000120
 3       44  Afghanistan  2012               0.016122
 4       44  Afghanistan  2013               0.016843
 ...    ...          ...   ...                    ...
 4279   267     Zimbabwe  2018               0.008564
 4280   267     Zimbabwe  2019               0.011827
 4281   267     Zimbabwe  2020               0.014070
 4282   267     Zimbabwe  2021               0.027941
 4283   267     Zimbabwe  2022               0.041249

 [4284 rows x 4 columns],
 'renovavel_consumida':       Code  Entity  Year  \
 0       45  Africa  1971
 1       45  Africa  1972
 2       45  Africa  1973
 3       45  Africa  1974
 4       45  Africa  1975
 ...    ...     ...   ...
 5690    43   World  2018
 5691    43   World  2019
 5692    43   World  2020
 5693    43   World  2021
 5694    43   World  2022

       Other renewables (including geothermal and biomass) electricity generation - TWh  \
 0                                               0.16400
 1                                               0.16500
 2                                               0.17000
 3                                               0.17500
 4                                               0.17200
 ...                                                 ...
 5690                                          636.21330
 5691                                          667.61945
 5692                                          702.98230
 5693                                          751.17690
 5694                                          776.85657

       Solar generation - TWh  Wind generation - TWh  Hydro generation - TWh
 0                    0.00000                 0.0000               26.013390
 1                    0.00000                 0.0000               29.633196
 2                    0.00000                 0.0000               31.345707
 3                    0.00000                 0.0000               35.667076
 4                    0.00000                 0.0000               37.717968
 ...                      ...                    ...                     ...
 5690               575.76025              1269.5287             4189.757000
 5691               705.22516              1420.6240             4243.287600
 5692               854.37476              1593.9530             4359.012000
 5693              1059.29370              1854.1052             4288.783000
 5694              1322.61570              2104.8396             4334.190000

 [5695 rows x 7 columns],
 'renovavel_produzida':       Code         Entity  Year  Electricity from wind (TWh)  \
 0      196  ASEAN (Ember)  2000                          0.0
 1      196  ASEAN (Ember)  2001                          0.0
 2      196  ASEAN (Ember)  2002                          0.0
 3      196  ASEAN (Ember)  2003                          0.0
 4      196  ASEAN (Ember)  2004                          0.0
 ...    ...            ...   ...                          ...
 8952   267       Zimbabwe  2017                          0.0
 8953   267       Zimbabwe  2018                          0.0
 8954   267       Zimbabwe  2019                          0.0
 8955   267       Zimbabwe  2020                          0.0
 8956   267       Zimbabwe  2021                          0.0

       Electricity from hydro (TWh)  Electricity from solar (TWh)  \
 0                            50.37                          0.00
 1                            54.26                          0.00
 2                            53.32                          0.00
 3                            53.28                          0.00
 4                            52.88                          0.00
 ...                            ...                           ...
 8952                          3.97                          0.01
 8953                          5.05                          0.02
 8954                          4.17                          0.03
 8955                          3.81                          0.03
 8956                          4.00                          0.04

       Other renewables including bioenergy (TWh)
 0                                          22.53
 1                                          22.42
 2                                          22.67
 3                                          22.43
 4                                          24.14
 ...                                          ...
 8952                                        0.32
 8953                                        0.39
 8954                                        0.38
 8955                                        0.35
 8956                                        0.38

 [8957 rows x 7 columns],
 'renovavel_compartilhada':       Code  Entity  Year  Renewables (% equivalent primary energy)
 0       45  Africa  1965                                  5.740281
 1       45  Africa  1966                                  6.113969
 2       45  Africa  1967                                  6.316580
 3       45  Africa  1968                                  6.994845
 4       45  Africa  1969                                  7.943916
 ...    ...     ...   ...                                       ...
 4782    43   World  2018                                 11.766204
 4783    43   World  2019                                 12.248977
 4784    43   World  2020                                 13.430855
 4785    43   World  2021                                 13.452535
 4786    43   World  2022                                 14.213598

 [4787 rows x 4 columns],
 'hidro_eletricidade_gerada':       Code         Entity  Year  Hydro (% electricity)
 0      196  ASEAN (Ember)  2000              13.663366
 1      196  ASEAN (Ember)  2001              13.660968
 2      196  ASEAN (Ember)  2002              12.610567
 3      196  ASEAN (Ember)  2003              11.915464
 4      196  ASEAN (Ember)  2004              10.904442
 ...    ...            ...   ...                    ...
 7005   267       Zimbabwe  2017              54.013607
 7006   267       Zimbabwe  2018              54.951040
 7007   267       Zimbabwe  2019              50.606796
 7008   267       Zimbabwe  2020              50.197628
 7009   267       Zimbabwe  2021              49.813200

 [7010 rows x 4 columns],
 'renovavel_eletricidade_gerada':       Code         Entity  Year  Renewables (% electricity)
 0      196  ASEAN (Ember)  2000                   19.774855
 1      196  ASEAN (Ember)  2001                   19.305622
 2      196  ASEAN (Ember)  2002                   17.972187
 3      196  ASEAN (Ember)  2003                   16.931679
 4      196  ASEAN (Ember)  2004                   15.882376
 ...    ...            ...   ...                         ...
 6827   267       Zimbabwe  2017                   58.503407
 6828   267       Zimbabwe  2018                   59.412407
 6829   267       Zimbabwe  2019                   55.582527
 6830   267       Zimbabwe  2020                   55.204216
 6831   267       Zimbabwe  2021                   55.043587

 [6832 rows x 4 columns],
 'solar_eletricidade_gerada':       Code         Entity  Year  Solar (% electricity)
 0      196  ASEAN (Ember)  2000               0.000000
 1      196  ASEAN (Ember)  2001               0.000000
 2      196  ASEAN (Ember)  2002               0.000000
 3      196  ASEAN (Ember)  2003               0.000000
 4      196  ASEAN (Ember)  2004               0.000000
 ...    ...            ...   ...                    ...
 6844   267       Zimbabwe  2017               0.136054
 6845   267       Zimbabwe  2018               0.217628
 6846   267       Zimbabwe  2019               0.364078
 6847   267       Zimbabwe  2020               0.395257
 6848   267       Zimbabwe  2021               0.498132

 [6849 rows x 4 columns],
 'eolica_eletricidade_gerada':       Code         Entity  Year  Wind (% electricity)
 0      196  ASEAN (Ember)  2000                   0.0
 1      196  ASEAN (Ember)  2001                   0.0
 2      196  ASEAN (Ember)  2002                   0.0
 3      196  ASEAN (Ember)  2003                   0.0
 4      196  ASEAN (Ember)  2004                   0.0
 ...    ...            ...   ...                   ...
 6881   267       Zimbabwe  2017                   0.0
 6882   267       Zimbabwe  2018                   0.0
 6883   267       Zimbabwe  2019                   0.0
 6884   267       Zimbabwe  2020                   0.0
 6885   267       Zimbabwe  2021                   0.0

 [6886 rows x 4 columns],
 'solar_consumida':       Code         Entity  Year  Electricity from solar (TWh)
 0      196  ASEAN (Ember)  2000                          0.00
 1      196  ASEAN (Ember)  2001                          0.00
 2      196  ASEAN (Ember)  2002                          0.00
 3      196  ASEAN (Ember)  2003                          0.00
 4      196  ASEAN (Ember)  2004                          0.00
 ...    ...            ...   ...                           ...
 7951   267       Zimbabwe  2017                          0.01
 7952   267       Zimbabwe  2018                          0.02
 7953   267       Zimbabwe  2019                          0.03
 7954   267       Zimbabwe  2020                          0.03
 7955   267       Zimbabwe  2021                          0.04

 [7956 rows x 4 columns],
 'solar_compartilhada':       Code  Entity  Year  Solar (% equivalent primary energy)
 0       45  Africa  1971                             0.000000
 1       45  Africa  1972                             0.000000
 2       45  Africa  1973                             0.000000
 3       45  Africa  1974                             0.000000
 4       45  Africa  1975                             0.000000
 ...    ...     ...   ...                                  ...
 4030    43   World  2018                             0.943791
 4031    43   World  2019                             1.139321
 4032    43   World  2020                             1.425945
 4033    43   World  2021                             1.670318
 4034    43   World  2022                             2.055119

 [4035 rows x 4 columns],
 'eolica_geracao':       Code         Entity  Year  Electricity from wind (TWh)
 0      196  ASEAN (Ember)  2000                          0.0
 1      196  ASEAN (Ember)  2001                          0.0
 2      196  ASEAN (Ember)  2002                          0.0
 3      196  ASEAN (Ember)  2003                          0.0
 4      196  ASEAN (Ember)  2004                          0.0
 ...    ...            ...   ...                          ...
 7991   267       Zimbabwe  2017                          0.0
 7992   267       Zimbabwe  2018                          0.0
 7993   267       Zimbabwe  2019                          0.0
 7994   267       Zimbabwe  2020                          0.0
 7995   267       Zimbabwe  2021                          0.0

 [7996 rows x 4 columns],
 'eolica_compartilhada':       Code  Entity  Year  Wind (% equivalent primary energy)
 0       45  Africa  1965                            0.000000
 1       45  Africa  1966                            0.000000
 2       45  Africa  1967                            0.000000
 3       45  Africa  1968                            0.000000
 4       45  Africa  1969                            0.000000
 ...    ...     ...   ...                                 ...
 4096    43   World  2018                            2.081022
 4097    43   World  2019                            2.295078
 4098    43   World  2020                            2.660295
 4099    43   World  2021                            2.923595
 4100    43   World  2022                            3.270562

 [4101 rows x 4 columns]}

In [7]:
biocombustivel_produzido = dfs_energia['biocombustivel_produzido']
hidro_compartilhada = dfs_energia['hidro_compartilhada']
hidro_compartilhada.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4787 entries, 0 to 4786
Data columns (total 4 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Code                                 4787 non-null   int64
 1   Entity                               4787 non-null   object
 2   Year                                 4787 non-null   int64
 3   Hydro (% equivalent primary energy)  4787 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 149.7+ KB

In [8]:
biocombustivel_produzido.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1134 entries, 0 to 1133
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Code                       1134 non-null   int64
 1   Entity                     1134 non-null   object
 2   Year                       1134 non-null   int64
 3   Biofuels production - TWh  1134 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 35.6+ KB

In [9]:
f.altera_colunas(dfs_energia, nomes_dataframes)

{'biocombustivel_produzido':       code       entity  year  biofuels_production_-_twh
 0        1  Africa (EI)  1990                   0.305102
 1        1  Africa (EI)  1991                   0.305102
 2        1  Africa (EI)  1992                   0.305290
 3        1  Africa (EI)  1993                   0.068617
 4        1  Africa (EI)  1994                   0.068617
 ...    ...          ...   ...                        ...
 1129    43        World  2018                1080.687900
 1130    43        World  2019                1139.786100
 1131    43        World  2020                1071.721200
 1132    43        World  2021                1121.722300
 1133    43        World  2022                1187.204300

 [1134 rows x 4 columns],
 'eolica_acumulada':       code       entity  year  wind_energy_capacity
 0       44  Afghanistan  2012               0.00010
 1       44  Afghanistan  2013               0.00010
 2       44  Afghanistan  2014               0.00010
 3       44  Afghanistan  2015               0.00010
 4       44  Afghanistan  2016               0.00010
 ...    ...          ...   ...                   ...
 3054    43        World  2018             564.51290
 3055    43        World  2019             620.84130
 3056    43        World  2020             731.65550
 3057    43        World  2021             824.17090
 3058    43        World  2022             898.82425

 [3059 rows x 4 columns],
 'hidro_compartilhada':       code  entity  year  hydro_(%_equivalent_primary_energy)
 0       45  Africa  1965                             5.740281
 1       45  Africa  1966                             6.113969
 2       45  Africa  1967                             6.316580
 3       45  Africa  1968                             6.994845
 4       45  Africa  1969                             7.943916
 ...    ...     ...   ...                                  ...
 4782    43   World  2018                             6.867884
 4783    43   World  2019                             6.855210
 4784    43   World  2020                             7.275157
 4785    43   World  2021                             6.762651
 4786    43   World  2022                             6.734592

 [4787 rows x 4 columns],
 'hidro_consumida':       code         entity  year  electricity_from_hydro_(twh)
 0      196  ASEAN (Ember)  2000                         50.37
 1      196  ASEAN (Ember)  2001                         54.26
 2      196  ASEAN (Ember)  2002                         53.32
 3      196  ASEAN (Ember)  2003                         53.28
 4      196  ASEAN (Ember)  2004                         52.88
 ...    ...            ...   ...                           ...
 8879   267       Zimbabwe  2017                          3.97
 8880   267       Zimbabwe  2018                          5.05
 8881   267       Zimbabwe  2019                          4.17
 8882   267       Zimbabwe  2020                          3.81
 8883   267       Zimbabwe  2021                          4.00

 [8884 rows x 4 columns],
 'capacidade_geotermal':       code  entity  year  geothermal_energy_capacity
 0       45  Africa  2000                       65.30
 1       45  Africa  2001                       65.30
 2       45  Africa  2002                       65.30
 3       45  Africa  2003                       65.30
 4       45  Africa  2004                      135.30
 ...    ...     ...   ...                         ...
 1039    43   World  2018                    13471.32
 1040    43   World  2019                    14089.46
 1041    43   World  2020                    14416.76
 1042    43   World  2021                    14695.61
 1043    43   World  2022                    14876.51

 [1044 rows x 4 columns],
 'capacidade_solar':       code       entity  year  solar_energy_capacity
 0       44  Afghanistan  2009               0.000002
 1       44  Afghanistan  2010               0.000102
 2       44  Afghanistan  2011               0.000120
 3       44  Afghanistan  2012               0.016122
 4       44  Afghanistan  2013               0.016843
 ...    ...          ...   ...                    ...
 4279   267     Zimbabwe  2018               0.008564
 4280   267     Zimbabwe  2019               0.011827
 4281   267     Zimbabwe  2020               0.014070
 4282   267     Zimbabwe  2021               0.027941
 4283   267     Zimbabwe  2022               0.041249

 [4284 rows x 4 columns],
 'renovavel_consumida':       code  entity  year  \
 0       45  Africa  1971
 1       45  Africa  1972
 2       45  Africa  1973
 3       45  Africa  1974
 4       45  Africa  1975
 ...    ...     ...   ...
 5690    43   World  2018
 5691    43   World  2019
 5692    43   World  2020
 5693    43   World  2021
 5694    43   World  2022

       other_renewables_(including_geothermal_and_biomass)_electricity_generation_-_twh  \
 0                                               0.16400
 1                                               0.16500
 2                                               0.17000
 3                                               0.17500
 4                                               0.17200
 ...                                                 ...
 5690                                          636.21330
 5691                                          667.61945
 5692                                          702.98230
 5693                                          751.17690
 5694                                          776.85657

       solar generation - twh  wind generation - twh  hydro generation - twh
 0                    0.00000                 0.0000               26.013390
 1                    0.00000                 0.0000               29.633196
 2                    0.00000                 0.0000               31.345707
 3                    0.00000                 0.0000               35.667076
 4                    0.00000                 0.0000               37.717968
 ...                      ...                    ...                     ...
 5690               575.76025              1269.5287             4189.757000
 5691               705.22516              1420.6240             4243.287600
 5692               854.37476              1593.9530             4359.012000
 5693              1059.29370              1854.1052             4288.783000
 5694              1322.61570              2104.8396             4334.190000

 [5695 rows x 7 columns],
 'renovavel_produzida':       code         entity  year  electricity_from_wind_(twh)  \
 0      196  ASEAN (Ember)  2000                          0.0
 1      196  ASEAN (Ember)  2001                          0.0
 2      196  ASEAN (Ember)  2002                          0.0
 3      196  ASEAN (Ember)  2003                          0.0
 4      196  ASEAN (Ember)  2004                          0.0
 ...    ...            ...   ...                          ...
 8952   267       Zimbabwe  2017                          0.0
 8953   267       Zimbabwe  2018                          0.0
 8954   267       Zimbabwe  2019                          0.0
 8955   267       Zimbabwe  2020                          0.0
 8956   267       Zimbabwe  2021                          0.0

       electricity from hydro (twh)  electricity from solar (twh)  \
 0                            50.37                          0.00
 1                            54.26                          0.00
 2                            53.32                          0.00
 3                            53.28                          0.00
 4                            52.88                          0.00
 ...                            ...                           ...
 8952                          3.97                          0.01
 8953                          5.05                          0.02
 8954                          4.17                          0.03
 8955                          3.81                          0.03
 8956                          4.00                          0.04

       other renewables including bioenergy (twh)
 0                                          22.53
 1                                          22.42
 2                                          22.67
 3                                          22.43
 4                                          24.14
 ...                                          ...
 8952                                        0.32
 8953                                        0.39
 8954                                        0.38
 8955                                        0.35
 8956                                        0.38

 [8957 rows x 7 columns],
 'renovavel_compartilhada':       code  entity  year  renewables_(%_equivalent_primary_energy)
 0       45  Africa  1965                                  5.740281
 1       45  Africa  1966                                  6.113969
 2       45  Africa  1967                                  6.316580
 3       45  Africa  1968                                  6.994845
 4       45  Africa  1969                                  7.943916
 ...    ...     ...   ...                                       ...
 4782    43   World  2018                                 11.766204
 4783    43   World  2019                                 12.248977
 4784    43   World  2020                                 13.430855
 4785    43   World  2021                                 13.452535
 4786    43   World  2022                                 14.213598

 [4787 rows x 4 columns],
 'hidro_eletricidade_gerada':       code         entity  year  hydro_(%_electricity)
 0      196  ASEAN (Ember)  2000              13.663366
 1      196  ASEAN (Ember)  2001              13.660968
 2      196  ASEAN (Ember)  2002              12.610567
 3      196  ASEAN (Ember)  2003              11.915464
 4      196  ASEAN (Ember)  2004              10.904442
 ...    ...            ...   ...                    ...
 7005   267       Zimbabwe  2017              54.013607
 7006   267       Zimbabwe  2018              54.951040
 7007   267       Zimbabwe  2019              50.606796
 7008   267       Zimbabwe  2020              50.197628
 7009   267       Zimbabwe  2021              49.813200

 [7010 rows x 4 columns],
 'renovavel_eletricidade_gerada':       code         entity  year  renewables_(%_electricity)
 0      196  ASEAN (Ember)  2000                   19.774855
 1      196  ASEAN (Ember)  2001                   19.305622
 2      196  ASEAN (Ember)  2002                   17.972187
 3      196  ASEAN (Ember)  2003                   16.931679
 4      196  ASEAN (Ember)  2004                   15.882376
 ...    ...            ...   ...                         ...
 6827   267       Zimbabwe  2017                   58.503407
 6828   267       Zimbabwe  2018                   59.412407
 6829   267       Zimbabwe  2019                   55.582527
 6830   267       Zimbabwe  2020                   55.204216
 6831   267       Zimbabwe  2021                   55.043587

 [6832 rows x 4 columns],
 'solar_eletricidade_gerada':       code         entity  year  solar_(%_electricity)
 0      196  ASEAN (Ember)  2000               0.000000
 1      196  ASEAN (Ember)  2001               0.000000
 2      196  ASEAN (Ember)  2002               0.000000
 3      196  ASEAN (Ember)  2003               0.000000
 4      196  ASEAN (Ember)  2004               0.000000
 ...    ...            ...   ...                    ...
 6844   267       Zimbabwe  2017               0.136054
 6845   267       Zimbabwe  2018               0.217628
 6846   267       Zimbabwe  2019               0.364078
 6847   267       Zimbabwe  2020               0.395257
 6848   267       Zimbabwe  2021               0.498132

 [6849 rows x 4 columns],
 'eolica_eletricidade_gerada':       code         entity  year  wind_(%_electricity)
 0      196  ASEAN (Ember)  2000                   0.0
 1      196  ASEAN (Ember)  2001                   0.0
 2      196  ASEAN (Ember)  2002                   0.0
 3      196  ASEAN (Ember)  2003                   0.0
 4      196  ASEAN (Ember)  2004                   0.0
 ...    ...            ...   ...                   ...
 6881   267       Zimbabwe  2017                   0.0
 6882   267       Zimbabwe  2018                   0.0
 6883   267       Zimbabwe  2019                   0.0
 6884   267       Zimbabwe  2020                   0.0
 6885   267       Zimbabwe  2021                   0.0

 [6886 rows x 4 columns],
 'solar_consumida':       code         entity  year  electricity_from_solar_(twh)
 0      196  ASEAN (Ember)  2000                          0.00
 1      196  ASEAN (Ember)  2001                          0.00
 2      196  ASEAN (Ember)  2002                          0.00
 3      196  ASEAN (Ember)  2003                          0.00
 4      196  ASEAN (Ember)  2004                          0.00
 ...    ...            ...   ...                           ...
 7951   267       Zimbabwe  2017                          0.01
 7952   267       Zimbabwe  2018                          0.02
 7953   267       Zimbabwe  2019                          0.03
 7954   267       Zimbabwe  2020                          0.03
 7955   267       Zimbabwe  2021                          0.04

 [7956 rows x 4 columns],
 'solar_compartilhada':       code  entity  year  solar_(%_equivalent_primary_energy)
 0       45  Africa  1971                             0.000000
 1       45  Africa  1972                             0.000000
 2       45  Africa  1973                             0.000000
 3       45  Africa  1974                             0.000000
 4       45  Africa  1975                             0.000000
 ...    ...     ...   ...                                  ...
 4030    43   World  2018                             0.943791
 4031    43   World  2019                             1.139321
 4032    43   World  2020                             1.425945
 4033    43   World  2021                             1.670318
 4034    43   World  2022                             2.055119

 [4035 rows x 4 columns],
 'eolica_geracao':       code         entity  year  electricity_from_wind_(twh)
 0      196  ASEAN (Ember)  2000                          0.0
 1      196  ASEAN (Ember)  2001                          0.0
 2      196  ASEAN (Ember)  2002                          0.0
 3      196  ASEAN (Ember)  2003                          0.0
 4      196  ASEAN (Ember)  2004                          0.0
 ...    ...            ...   ...                          ...
 7991   267       Zimbabwe  2017                          0.0
 7992   267       Zimbabwe  2018                          0.0
 7993   267       Zimbabwe  2019                          0.0
 7994   267       Zimbabwe  2020                          0.0
 7995   267       Zimbabwe  2021                          0.0

 [7996 rows x 4 columns],
 'eolica_compartilhada':       code  entity  year  wind_(%_equivalent_primary_energy)
 0       45  Africa  1965                            0.000000
 1       45  Africa  1966                            0.000000
 2       45  Africa  1967                            0.000000
 3       45  Africa  1968                            0.000000
 4       45  Africa  1969                            0.000000
 ...    ...     ...   ...                                 ...
 4096    43   World  2018                            2.081022
 4097    43   World  2019                            2.295078
 4098    43   World  2020                            2.660295
 4099    43   World  2021                            2.923595
 4100    43   World  2022                            3.270562

 [4101 rows x 4 columns]}

In [10]:
f.verifica_tamanho_coluna(dfs_energia, nomes_dataframes)

A coluna 4 do dataframe biocombustivel_produzido está dentro do tamanho permitido
A coluna 4 do dataframe eolica_acumulada está dentro do tamanho permitido
A coluna 4 do dataframe hidro_compartilhada está dentro do tamanho permitido
A coluna 4 do dataframe hidro_consumida está dentro do tamanho permitido
A coluna 4 do dataframe capacidade_geotermal está dentro do tamanho permitido
A coluna 4 do dataframe capacidade_solar está dentro do tamanho permitido
A coluna other_renewables_(including_geothermal_and_biomass)_electricity_generation_-_twh do dataframe renovavel_consumida possui mais de 64 caracteres
A coluna 4 do dataframe renovavel_produzida está dentro do tamanho permitido
A coluna 4 do dataframe renovavel_compartilhada está dentro do tamanho permitido
A coluna 4 do dataframe hidro_eletricidade_gerada está dentro do tamanho permitido
A coluna 4 do dataframe renovavel_eletricidade_gerada está dentro do tamanho permitido
A coluna 4 do dataframe solar_eletricidade_gerada está dentro do tamanho permitido
A coluna 4 do dataframe eolica_eletricidade_gerada está dentro do tamanho permitido
A coluna 4 do dataframe solar_consumida está dentro do tamanho permitido
A coluna 4 do dataframe solar_compartilhada está dentro do tamanho permitido
A coluna 4 do dataframe eolica_geracao está dentro do tamanho permitido
A coluna 4 do dataframe eolica_compartilhada está dentro do tamanho permitido

In [15]:
nome_col = "other_renewables_(including_geothermal_and_biomass)_electricity_generation_-_twh"
novo_nome = "oth_renewables_(incl_geo_n_biomass)_electricity_generation_-_twh"
len(novo_nome)

64

In [11]:
f.renomear_coluna(dfs_energia, 'renovavel_consumida', 'oth_renewables_(incl_geo_n_biomass)_electricity_generation_-_twh')
f.verifica_tamanho_coluna(dfs_energia, nomes_dataframes)

A coluna 4 do dataframe biocombustivel_produzido está dentro do tamanho permitido
A coluna 4 do dataframe eolica_acumulada está dentro do tamanho permitido
A coluna 4 do dataframe hidro_compartilhada está dentro do tamanho permitido
A coluna 4 do dataframe hidro_consumida está dentro do tamanho permitido
A coluna 4 do dataframe capacidade_geotermal está dentro do tamanho permitido
A coluna 4 do dataframe capacidade_solar está dentro do tamanho permitido
A coluna 4 do dataframe renovavel_consumida está dentro do tamanho permitido
A coluna 4 do dataframe renovavel_produzida está dentro do tamanho permitido
A coluna 4 do dataframe renovavel_compartilhada está dentro do tamanho permitido
A coluna 4 do dataframe hidro_eletricidade_gerada está dentro do tamanho permitido
A coluna 4 do dataframe renovavel_eletricidade_gerada está dentro do tamanho permitido
A coluna 4 do dataframe solar_eletricidade_gerada está dentro do tamanho permitido
A coluna 4 do dataframe eolica_eletricidade_gerada está dentro do tamanho permitido
A coluna 4 do dataframe solar_consumida está dentro do tamanho permitido
A coluna 4 do dataframe solar_compartilhada está dentro do tamanho permitido
A coluna 4 do dataframe eolica_geracao está dentro do tamanho permitido
A coluna 4 do dataframe eolica_compartilhada está dentro do tamanho permitido

In [ ]:
f.salva_csv(dfs_energia, nomes_dataframes)